# Generated by Django 4.0.2 on 2022-03-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
