# Generated by Django 4.0.2 on 2022-03-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_car_seller_mobile_buycar'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_status',
            field=models.CharField(default='sell', max_length=20),
        ),
    ]
