# Generated by Django 4.0.2 on 2022-03-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_car_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold')], default='Available', max_length=20),
        ),
    ]
